# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05eadf3fd744bde838c2735e277cd0d6507b4d0c64f8aae8dcbd4cd7abd29c6a0cd6c1c9b04d14521496b51aa13b876fefc3b8fae5322bed055288417644d634

test:
  secret_key_base: 158147ec630031f942dae028269be063fa66cc3a41447e6c7b7820a0cb3e955a63f7f1a4235e4550f2af85a8b837400ed96fd1a3f806a8a986e95d3f837f7ea5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
